settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: 'Some checks failed'

monitors:
  - id: ego-jveres-me # unique identifier
    name: ego.jveres.me
    description: 'Ego graph frontend service' # default=empty
    url: 'https://ego.jveres.me' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: egonet-fly-dev
    name: egonet.fly.dev
    description: 'Ego graph network service'
    url: 'https://egonet.fly.dev'
    method: GET
    expectStatus: 200
